[package]
name = "pdf-handler"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
hayro-syntax = "0.4.0"
hayro = "0.4.0"
krilla = { version = "0.5.0", features = ["pdf"] }
anyhow = "1.0"
tiny-skia = "0.11"
image = "0.25"
